source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target ‘Runner’ do

pod 'Kingfisher’
pod 'SnapKit', '~> 3.2.0'
pod 'EZSwiftExtensions'

# mark: 高德 iOS SDK
pod 'AMap3DMap-NO-IDFA'
pod 'AMapSearch-NO-IDFA'
pod 'AMapLocation-NO-IDFA'

pod 'TZImagePickerController'
pod 'DZNEmptyDataSet'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
end
